name: eds217_2025
channels:
  - conda-forge
dependencies:
  # Core Python
  - python=3.11
  
  # Essential Data Science Libraries (with minimum versions for stability)
  - numpy>=2.3,<3.0
  - pandas>=2.3,<3.0
  - matplotlib>=3.9,<4.0
  - seaborn>=0.13,<1.0
  
  # Jupyter Ecosystem
  - jupyter
  - jupyterlab>=4.4,<5.0
  - ipykernel>=6.30
  
  # Scientific Computing
  - scipy>=1.11
  
  # Additional Useful Libraries (Optional but Recommended)
  - requests>=2.31           # Web data access, API calls
  - beautifulsoup4>=4.12     # Web scraping, HTML parsing
  - openpyxl>=3.1           # Excel file support (.xlsx)
  - xlrd>=2.0               # Legacy Excel file support (.xls)
  - lxml>=4.9               # XML/HTML parsing (faster than built-in)
  - plotly>=5.17            # Interactive visualizations
  - scikit-learn>=1.3       # Basic machine learning tools
  - statsmodels>=0.14       # Statistical modeling
  
  # Development Tools
  - pip                     # Package installer 