---
title: "Day 5: 🙌 Coding Colab Answer Key"
subtitle: "Cleaning Pandas"
search: false
---

## Introduction

In this collaborative coding exercise, you will work together and apply your new data cleaning skills to a simple dataframe that has a suprising number of problems. 

## Resources

Here's our course cheatsheet on cleaning data:

- [Pandas Cleaning Cheatsheet](../cheatsheets/data_cleaning.qmd)

Feel free to refer to this cheatsheet throughout the exercise if you need a quick reminder about syntax or functionality.

## Setup

First, let's import the necessary libraries and load an example messy dataframe.

```{python}
import pandas as pd
import numpy as np

url = 'https://bit.ly/messy_csv'
messy_df = pd.read_csv(url)
```


## Practical Exercise: Cleaning a Messy Environmental Dataset

Let's apply what we've learned so far to clean the messy environmental dataset. 

Your task is to clean this dataframe by

1. Removing duplicates

```{python}
#| echo: true
#| include: true
messy_df.drop_duplicates(inplace=True)
```

2. Handling missing values (either fill or dropna to remove rows with missing data)

```{python}
#| echo: true
#| include: true
messy_df = messy_df.dropna()
```

3. Ensuring consistent data types (dates, strings)

```{python}
#| echo: true
#| include: true
messy_df['site'] = messy_df['site'].astype('string')
messy_df['collection date'] = pd.to_datetime(messy_df['collection date'])
```

4. Formatting the 'site' column for consistency

```{python}
#| echo: true
#| include: true
messy_df['site'] = messy_df['site'].str.lower().replace('sitec','site_c')
```

5. Making sure all column names are lower case, without whitespace.
```{python}
#| echo: true
#| include: true
messy_df.rename(columns={'collection date': 'collection_date'}, inplace=True)
```

Try to implement these steps using the techniques we've learned.

```{python}
#| echo: true
#| include: true
cleaned_df = messy_df.copy()

print("Cleaned DataFrame:")
print(cleaned_df)

print("\nCleaned dtypes:")
print(cleaned_df.dtypes)
```

::: {.center-text .body-text-xl .teal-text}
End Coding Colab Session (Day 4)
:::

