---
title: "Answer Keys"
subtitle: "Keys to Colab, Live Coding, and End of Day Activities"
jupyter: eds217_2025
search: false
format: 
    html:
        toc: true
        toc-depth: 2
---

## 🙌 Coding Colab Answer Keys

- [Session 2C: Working with lists, dictionaries, and sets](2c_lists_dictionaries_sets-key.qmd)
- [Session 3B: Control Flows](3b_control_flows-key.qmd)
- [Session 5C: Cleaning Data](5c_cleaning_data-key.qmd)
- [Session 7C: Visualizations](7c_visualizations-key.qmd)

## End of Day Activities

- [Day 1: Example Python Data Science Workflow](eod-day1-key.qmd)
- [Day 2: Python Data Structures Practice](eod-day2-key.qmd)
- [Day 3: Using Pandas Series for Data Analysis](eod-day3-key.qmd)
- [Day 4: Reading, Filtering, and Visualizing Data in Pandas](eod-day4-key.qmd)
- [Day 5: Exploring the Banana Index](eod-day5-key.qmd)
- [Day 6: Eurovision Data Analysis Exercise](eod-day6-key.qmd)
- [Day 7: Plant Hardiness Zones](eod-day7-key.qmd)

## Live Coding Session Notes

- [Session 2D: List Comprehensions](../live-coding/2d_list_comprehensions_notes.qmd) (NOTE: Not in course schedule)
- [Session 3A: Control Flows](../live-coding/3a_control_flows_notes.qmd)
- [Session 4B: Exploring DataFrames](../live-coding/4b_exploring_dataframes_notes.qmd)
- [Session 4D: Data Import and Export](../live-coding/4b_exploring_dataframes_notes.qmd)
- [Session 5A: Selecting and Filtering](../live-coding/5a_selecting_and_filtering_notes.qmd)
