---
title: "Day 3: Tasks & activities"
subtitle: "Vectors by hand and in R, git practice"
---

## Part 1: By hand problems

#### Derivative reminder

Biomass (grams) in a reactor over time (hours) is described by: 

::: {.center-text}
$$B(t) = 0.4t^2 + 3.6$$
:::

a. What is the biomass in the reactor after 4 hours?
b. What is the rate at which biomass is changing in the reactor at t = 3.2 hours? 

#### Vector math

For the vectors $\vec a = (1,6)$ and $\vec b = (2, 4)$: 

a. Find and sketch $\vec a + \vec b$
b. Find and sketch $\vec b - \vec a$
c. Find and sketch $4 \vec a$
d. Find $\vec a \cdot \vec b$

## Part 2: Coding practice

a. Create a new project (you may want to name it `eds212-day3-tasks` or something similar)
b. Setup your local and remote repo using `usethis::use_git()` and `usethis::use_github()`
c. In a Quarto doc in your project:
  - Using the `c()` function, create and store two new vectors, called `vec_a` and   `vec_b`, where $\vec a = (1,6)$ and $\vec b = (2, 4)$: 
  - Check your by-hand solutions from Part 1 by finding the following in R: 
    - $\vec a + \vec b$
    - $\vec b - \vec a$
    - $4 \vec a$
    - $\vec a \cdot \vec b$
d. Save your quarto doc and Render
e. Open the Terminal outside of RStudio
f. Navigate to your project directory
c. Use git status (or checkout...) to check the status
d. Use `git add .` to stage all changes 
e. Use `git commit -m "your commit message here"` to commit to your local repo
f. Use `git pull` to check for remote changes
g. Use `git push` to push changes to your remote repo
h. Go to your remote repo for the project and check to see that the new updates are stored

## Part 3: Fork & clone a repo, use the code

a. Fork and clone [this repo](https://github.com/EDS-212-Essential-Math/SIR-ODE-example), which contains an R Markdown document with code to numerically solve the SIR equations, to create a version-controlled project
b. Once you've created your project, open the `sir-example.Rmd` file. 
c. Run all code in the .Rmd (Cmd + Option + R, or go up to the run button and choose the last option "Run All")
d. Explore the code and output graph. What is the code doing? What is the graph telling us? 
e. Make small changes to the parameter values to see how the SIR models change. Are the changes expected? 
f. After trying out a few changes, save and knit your new output graph.
g. Stage, commit, pull, then push to your repo **in the command line**.
h. Check for your changes on GitHub. Are they there? Cool, done with Part 3.

::: {.center-text .body-text-xl .teal-text}
End Activity Session (Day 3)
:::



